[2024-03-25T09:15:17.552+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_java_jar2.task_2 manual__2024-03-25T09:15:14.113592+00:00 [queued]>
[2024-03-25T09:15:17.566+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_java_jar2.task_2 manual__2024-03-25T09:15:14.113592+00:00 [queued]>
[2024-03-25T09:15:17.566+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-25T09:15:17.582+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): task_2> on 2024-03-25 09:15:14.113592+00:00
[2024-03-25T09:15:17.587+0000] {standard_task_runner.py:60} INFO - Started process 289 to run task
[2024-03-25T09:15:17.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deploy_java_jar2', 'task_2', 'manual__2024-03-25T09:15:14.113592+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/execute.py', '--cfg-path', '/tmp/tmpcav404d6']
[2024-03-25T09:15:17.593+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask task_2
[2024-03-25T09:15:17.647+0000] {task_command.py:423} INFO - Running <TaskInstance: deploy_java_jar2.task_2 manual__2024-03-25T09:15:14.113592+00:00 [running]> on host aaae036974ec
[2024-03-25T09:15:17.742+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_java_jar2' AIRFLOW_CTX_TASK_ID='task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T09:15:14.113592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T09:15:14.113592+00:00'
[2024-03-25T09:15:17.744+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-25T09:15:17.745+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/handle/query1.py']
[2024-03-25T09:15:17.763+0000] {subprocess.py:86} INFO - Output:
[2024-03-25T09:15:17.820+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-03-25T09:15:17.820+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/handle/query1.py", line 1, in <module>
[2024-03-25T09:15:17.821+0000] {subprocess.py:93} INFO -     from clickhouse_driver import Client
[2024-03-25T09:15:17.821+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'clickhouse_driver'
[2024-03-25T09:15:17.825+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-25T09:15:17.840+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-25T09:15:17.844+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_java_jar2, task_id=task_2, execution_date=20240325T091514, start_date=20240325T091517, end_date=20240325T091517
[2024-03-25T09:15:17.862+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task task_2 (Bash command failed. The command returned a non-zero exit code 1.; 289)
[2024-03-25T09:15:17.883+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T09:15:17.912+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
